development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: help@1docway.com
  :password: fooBar!23
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: help@1docway.com
  :password: fooBar!23
  :enable_starttls_auto: true